# HyprMode - Float and center
windowrule = float true, match:class hyprmode
windowrule = center on, match:class hyprmode
windowrule = size 600 530, match:class hyprmode
windowrule = opacity 0.95, match:class hyprmode
# window should float by default
windowrule = float on, center on, match:tag centered-floating-window
windowrule = tag +centered-floating-window, match:class ^soffice$ match:title Text\ Import

